# Generated by Django 6.1 on 2026-08-27 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='history',
            name='answer',
            field=models.ForeignKey(blank=True, db_column='answer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='core.answer'),
        ),
        migrations.AlterField(
            model_name='ingestlog',
            name='document',
            field=models.ForeignKey(blank=True, db_column='document_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingest_logs', to='core.document'),
        ),
    ]
