# Generated by Django 6.1 on 2026-08-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_document_options_alter_history_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['page'], name='chunks_page_e0a5c3_idx'),
        ),
    ]
