# Generated by Django 6.1 on 2026-09-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_page_to_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_ocr',
            field=models.BooleanField(default=False),
        ),
    ]
