# Generated by Django 6.1 on 2026-09-26 15:50

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_ingestlog_status_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chunks_search_vector_gin'),
        ),
        migrations.RunSQL(
            sql="""
            UPDATE chunks SET search_vector = to_tsvector('pg_catalog.simple', coalesce(chunk_text, ''));
            CREATE TRIGGER chunk_search_vector_update
            BEFORE INSERT OR UPDATE OF chunk_text ON chunks
            FOR EACH ROW EXECUTE FUNCTION
            tsvector_update_trigger(search_vector, 'pg_catalog.simple', chunk_text);
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS chunk_search_vector_update ON chunks;
            """,
        ),
    ]
